// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller

import { application } from "./application"

import Admin__ServerConsoleController from "./admin/server_console_controller"
application.register("admin--server-console", Admin__ServerConsoleController)
