Style/AlignArray:
  Enabled: false
Style/AlignHash:
  Enabled: false
Style/AlignParameters:
  Enabled: false
Style/StringLiterals:
  Enabled: false
Style/MultilineOperationIndentation:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Style/ClosingParenthesisIndentation:
  Enabled: false
LineLength:
  Max: 80
ExtraSpacing:
  Enabled: false
AbcSize:
  Enabled: false
Style/SpaceBeforeFirstArg:
  Enabled: false
AmbiguousOperator:
  Enabled: false
MultilineMethodCallIndentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
