language: ruby
rvm:
  - 2.5.3

addons:
  postgresql: 9.6

services:
  - redis-server

cache:
  bundler: true
  directories:
  - node_modules # NPM packages

before_script:
  - cp config/secrets.yml.ci config/secrets.yml
  - cp config/database.yml.example config/database.yml
  - psql -c 'create database athensmc_test;' -U postgres
